import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {stories, menu} from './content.mjs';
import {siteUrl, socialMetadata} from './social.mjs';
const root = path.dirname(fileURLToPath(import.meta.url)), out = path.join(root, 'dist');
await fs.mkdir(path.join(out, 'assets'), {recursive: true});
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const brand = '<span>OneBe</span> salon';
const eyebrow = text => `<p class="eyebrow">${text}<span aria-hidden="true"></span></p>`;
const textLink = (text, href) => `<a class="text-link" href="${href}"><span>${text}</span><i aria-hidden="true"></i></a>`;
const image = (file, alt, cls = '') => `<img class="${cls}" src="./assets/${file}" alt="${alt}" loading="lazy" decoding="async" width="1536" height="1024">`;
function header(home = false) {
 return `<a class="skip-link" href="#main">本文へ移動</a><header class="site-header ${home ? 'home-header' : ''}"><a class="brand" href="./" aria-label="OneBe salon トップ">${brand}</a><div class="header-actions"><button class="header-reserve" data-dialog="reservation">Reservation <span aria-hidden="true"></span></button><button class="menu-toggle" data-dialog="navigation" aria-label="メニューを開く" aria-controls="navigation" aria-expanded="false"><span></span><span></span><span></span></button></div></header>`;
}
const legal = `<footer class="site-footer"><a href="./" class="footer-brand">OneBe salon</a><p>架空のサロンのデザインサンプルです。画像はイメージであり、実店舗・施術実績ではありません。</p><small>© 2026 OneBe.inc</small></footer>`;
const reservation = `<section class="reservation-section" id="reservation-section" aria-labelledby="reservation-heading"><div class="reservation-shadow" aria-hidden="true"></div><div class="reservation-copy">${eyebrow('RESERVATION')}<h2 id="reservation-heading">美しい日常は、<br>ここからはじまる。</h2></div><div class="reservation-action"><p>ご予約・お問い合わせは<br>こちらから。</p><button class="outline-button" data-dialog="reservation">WEB予約する<span aria-hidden="true"></span></button></div><p class="micro reservation-micro">ONE BE<br>A BRIGHTER<br>YOU</p></section>`;
const dialogs = `<dialog id="navigation" class="navigation-dialog" aria-labelledby="navigation-title"><button class="dialog-close" aria-label="メニューを閉じる">×</button><p id="navigation-title" class="brand">${brand}</p><nav aria-label="サイトメニュー"><a href="./#concept"><span>01</span>Our concept<small>私たちの想い</small></a><a href="./menu.html"><span>02</span>Menu<small>メニューと料金</small></a><a href="./#space"><span>03</span>Space<small>サロンの空間</small></a><a href="./article.html"><span>04</span>Journal<small>読み物</small></a><a href="./information.html"><span>05</span>Information<small>お知らせ</small></a></nav><button class="outline-button dark-button" data-dialog="reservation">ご予約のご案内<span aria-hidden="true"></span></button><p class="dialog-note">HAIR. LIFE. FOR A CALMER YOU.</p></dialog><dialog id="reservation" class="info-dialog" aria-labelledby="reservation-title"><button class="dialog-close" aria-label="閉じる">×</button>${eyebrow('RESERVATION')}<h2 id="reservation-title">ご予約のご案内</h2><p>OneBe salonをご覧いただき、<br>ありがとうございます。</p><p>こちらは架空のサロンのデザインサンプルです。<br>実際のご予約・お問い合わせは受け付けていません。</p><button class="outline-button dark-button dialog-close-button">サイトに戻る<span aria-hidden="true"></span></button></dialog>`;
const home = `${header(true)}<main id="main">
<section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="hero-text"><h1 id="hero-title">髪が整うと、<br>わたしが整う。</h1><div class="hero-line" aria-hidden="true"></div><p class="hero-lead">日常に、<br>やさしい余白をつくる場所。</p><p class="micro hero-micro">HAIR<br>LIFE<br>FOR A CALMER YOU</p></div><a class="scroll-cue" href="#concept"><span>SCROLL</span><i aria-hidden="true"></i></a></div><div class="hero-visual"><img class="hero-image" src="./assets/salon-hero.webp" width="1448" height="1086" alt="自然光が差し込む、緑と木の温もりに包まれたOneBe salonの店内イメージ" fetchpriority="high" decoding="async"><p class="hero-caption">美しさは、<br>暮らしのなかにある。</p><button class="motion-toggle" aria-label="写真の動きを一時停止" aria-pressed="false"><span aria-hidden="true">Ⅱ</span></button></div></section>
<section class="concept-section" id="concept" aria-labelledby="concept-title"><span id="about" class="anchor-alias"></span><div class="concept-visual"><img src="./assets/botanical.webp" alt="" loading="lazy" width="1536" height="1024"><p class="visual-brand">${brand}</p><div class="concept-visual-copy"><p>髪を通して、<br>わたしらしい毎日をつくる。</p><p class="micro">A MORE YOU.<br>A BRIGHTER TOMORROW.</p></div></div><div class="concept-content"><div class="concept-copy reveal">${eyebrow('OUR CONCEPT')}<h2 id="concept-title">美しさは、<br>生き方の一部。</h2><p>OneBe salonは、髪を整えるだけでなく、<br class="desktop-break">毎日を少しやさしく、心地よくするための場所です。<br class="desktop-break">丁寧なカウンセリングと、上質な空間で<br class="desktop-break">あなたらしい美しさを引き出します。</p>${textLink('私たちの想い', './concept.html')}</div><div class="concept-detail"><img src="./assets/botanical.webp" alt="光と影が揺れるオリーブの葉のイメージ" loading="lazy" width="1536" height="1024"><p class="micro">BEAUTY<br>LIVES<br>IN<br>YOUR<br>DAILY LIFE</p><i aria-hidden="true"></i></div></div></section>
<section class="menu-section" id="menu" aria-labelledby="menu-title"><div class="menu-content"><div class="menu-copy reveal">${eyebrow('MENU')}<h2 id="menu-title">髪と、<br>これからをつくる。</h2><p>一人ひとりのライフスタイルに寄り添い、<br>髪本来の美しさを引き出すメニューをご用意しています。</p>${textLink('すべてのメニューを見る', './menu.html')}</div><dl class="menu-preview">${[['CUT','カット','¥6,600〜','cut'],['COLOR','カラー','¥8,800〜','color'],['TREATMENT','トリートメント','¥5,500〜','treatment'],['HEAD SPA','ヘッドスパ','¥6,600〜','head-spa']].map(([en,ja,price,id])=>`<div><dt><a href="./menu.html#${id}">${en}<small>${ja}</small></a></dt><dd>${price}</dd></div>`).join('')}</dl></div><div class="menu-visual">${image('chair.webp', '木の椅子と、床に落ちる木漏れ日のイメージ')}<p class="menu-visual-copy">髪を整える時間が、<br>心まで満たしていく。</p><p class="micro">MORE<br>THAN<br>A HAIR SALON</p><a class="gallery-link" href="#space" aria-label="サロンの空間を見る"><span aria-hidden="true"></span>01 / 04</a></div></section>
<section class="space-section" id="space" aria-labelledby="space-title"><span id="salon" class="anchor-alias"></span><span id="style" class="anchor-alias"></span><div class="space-main"><img src="./assets/salon-hero.webp" alt="大きな窓のそばの、緑に囲まれた待合スペースのイメージ" loading="lazy" width="1448" height="1086"><div class="space-copy reveal">${eyebrow('SPACE')}<h2 id="space-title">光と、緑と、<br>やさしい時間。</h2><p>大きな窓から差し込む自然光、<br>やわらかな緑、心地よい距離感。<br>日常を忘れて、リラックスできる空間です。</p>${textLink('空間を見る','./space.html')}</div></div><div class="space-shelf">${image('salon-hero.webp','ヘアケアアイテムが並ぶ店内の棚のイメージ')}</div><div class="space-sign">${image('sign.webp','OneBe salonの壁面ロゴのイメージ')}<p class="micro">A QUIET PLACE<br>FOR A BRIGHTER YOU</p></div></section>
${reservation}</main>${legal}`;
const titleBlock = (en, title, intro) => `<div class="page-title">${eyebrow(en)}<h1>${title}</h1><p>${intro}</p></div>`;
const wrap = body => `${header()}<main id="main" class="inner-main">${body}</main>${reservation}${legal}`;
const menuPage = wrap(`${titleBlock('MENU & PRICE','メニューと料金','髪と、これからをつくる。')}<p class="page-note">税込の参考料金です。実際の施術・予約は受け付けていません。</p><nav class="menu-tabs" aria-label="メニュー分類">${menu.map(m=>`<a href="#${m.id}">${m.en}</a>`).join('')}</nav>${menu.map(m=>`<section id="${m.id}" class="price-category">${m.id === 'treatment' ? '<span id="care" class="anchor-alias"></span>' : ''}<div><h2>${m.en}</h2><p>${m.ja}</p></div><div class="price-list">${m.items.map(([name,price])=>`<div><h3>${name}</h3><span>${price}</span></div>`).join('')}<p>${m.note}</p></div></section>`).join('')}`);
const conceptPage = wrap(`${titleBlock('OUR CONCEPT','美しさは、生き方の一部。','髪を通して、わたしらしい毎日をつくる。')}<div class="editorial-layout">${image('botanical.webp','オリーブの葉とやわらかな光のイメージ')}<div><h2>日常に、やさしい余白を。</h2><p>OneBe salonは、髪を整えるだけでなく、毎日を少しやさしく、心地よくするための場所です。</p><p>大きく変える日も、いつも通りに整える日も。好みや髪の悩み、いつものお手入れについて、ゆっくり言葉にする時間を大切にしています。</p><h2>あなたらしい美しさを、一緒に。</h2><p>一人ひとりのライフスタイルに寄り添うカウンセリングと、自然光に包まれた空間。サロンを出たあとも続く、心地よい毎日を考えます。</p>${textLink('メニューを見る','./menu.html')}</div></div>`);
const spacePage = wrap(`${titleBlock('OUR SPACE','光と、緑と、やさしい時間。','心地よい余白のある、サロンの空間。')}<div class="space-gallery"><figure>${image('salon-hero.webp','自然光に包まれたサロンの店内イメージ')}<figcaption>01 / 大きな窓から差し込む、やわらかな光。</figcaption></figure><figure>${image('botanical.webp','オリーブの葉と木漏れ日のイメージ')}<figcaption>02 / ふと目を向ける、緑のある景色。</figcaption></figure><figure>${image('chair.webp','木の温もりを感じる椅子のイメージ')}<figcaption>03 / 木の温もりと、ほっとひと息つく時間。</figcaption></figure><figure>${image('sign.webp','OneBe salonの壁面ロゴのイメージ')}<figcaption>04 / あなたらしく過ごせる場所。</figcaption></figure></div><p class="page-note">掲載画像はサロンのデザインイメージです。実店舗の写真ではありません。</p>`);
const storyFiles = ['announcement','story','recruit'];
const storyCards = (info=false) => stories.map((s,i) => info && i===1 ? '' : `<a class="journal-card" href="./${storyFiles[i]}.html"><p class="eyebrow">${s.category} / ${s.date}</p><h2>${s.title}</h2><span class="text-link">続きを読む →</span></a>`).join('');
const journalPage = info => wrap(`${titleBlock(info?'INFORMATION':'JOURNAL',info?'お知らせ':'OneBe salonのノート。',info?'サンプルサイトからのご案内です。':'髪のこと、サロンのこと。日常に寄り添う小さなノート。')}<div class="journal-grid">${storyCards(info)}</div>`);
const storyPage = i => wrap(`${titleBlock(stories[i].category,stories[i].title,stories[i].lead)}<article class="story-body">${stories[i].paragraphs.map(p=>`<p>${p}</p>`).join('')}${textLink('読み物一覧に戻る','./article.html')}</article>`);
const pages = [['index','髪が整うと、わたしが整う。',home],['concept','私たちの想い',conceptPage],['space','サロンの空間',spacePage],['menu','メニューと料金',menuPage],['article','読み物',journalPage(false)],['information','お知らせ',journalPage(true)],...stories.map((s,i)=>[storyFiles[i],s.title,storyPage(i)])];
function html(name,title,body) {
 const fullTitle=`${title}｜OneBe salon`;
 const description=name==='index'?'髪が整うと、わたしが整う。OneBe salonは、日常にやさしい余白をつくるヘアサロンのデザインサンプル。コンセプト、メニュー、光と緑に包まれた空間をご紹介します。':`${title}。OneBe salonのデザインサンプルサイトです。`;
 const canonical=siteUrl+(name==='index'?'':`${name}.html`);
 return `<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}">${socialMetadata(fullTitle,description,name)}<meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f5f2ec"><link rel="icon" href="./favicon.svg"><link rel="preload" href="./assets/salon-serif.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="./styles.css?v=20260924">${name==='index'?'<link rel="preload" href="./assets/salon-hero.webp" as="image" fetchpriority="high">':''}<script>document.documentElement.classList.add('js');window.salonStart=performance.now();</script><script src="./app.js?v=20260924" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage','@id':canonical+'#webpage',url:canonical,name:fullTitle,description,inLanguage:'ja'})}</script></head><body class="${name==='index'?'home-page':'inner-page'}">${name==='index'?`<div class="loading-screen" aria-hidden="true"><div class="loading-brand">${brand}</div><p>HAIR. LIFE. FOR A CALMER YOU.</p><span></span></div>`:''}${body}${dialogs}</body></html>\n`;
}
for(const [name,title,body] of pages) await fs.writeFile(path.join(out,`${name}.html`),html(name,title,body));
for(const file of ['styles.css','app.js','favicon.svg']) await fs.copyFile(path.join(root,file),path.join(out,file));
for(const file of await fs.readdir(path.join(root,'assets'))) if(/\.(webp|woff2|jpg|png|txt)$/i.test(file) && !['salon-hero.png','botanical.png','chair.png','sign.png'].includes(file)) await fs.copyFile(path.join(root,'assets',file),path.join(out,'assets',file));
await fs.writeFile(path.join(out,'.nojekyll'),'');
await fs.writeFile(path.join(out,'404.html'),`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>ページが見つかりません｜OneBe salon</title></head><body style="background:#f5f2ec;color:#172338;font-family:serif;padding:12vw"><p>OneBe salon</p><h1>ページが見つかりません。</h1><p>URLをご確認いただくか、トップページへお戻りください。</p><a href="/sample_salon2/">トップページへ</a></body></html>`);
console.log(`Built ${pages.length} pages + 404. Existing noindex policy preserved.`);
